defmodule ICal.Event do
  @moduledoc """
  An iCalendar Event
  """

  # credo:disable-for-next-line
  defstruct uid: nil,
            dtstamp: nil,
            created: nil,
            dtstart: nil,
            dtend: nil,
            modified: nil,
            recurrence_id: nil,
            exdates: [],
            rdates: [],
            rrule: nil,
            class: nil,
            description: nil,
            duration: nil,
            location: nil,
            status: nil,
            organizer: nil,
            sequence: nil,
            summary: nil,
            url: nil,
            geo: nil,
            priority: nil,
            transparency: nil,
            alarms: [],
            attachments: [],
            attendees: [],
            categories: [],
            comments: [],
            contacts: [],
            related_to: [],
            resources: [],
            request_status: [],
            custom_properties: %{}

  @type t :: %__MODULE__{
          uid: String.t() | nil,
          dtstamp: ICal.optional_rfc5455_datetime,
          created: ICal.optional_rfc5455_datetime,
          dtstart: ICal.optional_rfc5455_date,
          dtend: ICal.optional_rfc5455_date,
          modified: ICal.optional_rfc5455_date,
          recurrence_id: ICal.optional_rfc5455_date,
          exdates: [Date.t() | ICal.rfc5455_datetime],
          rdates: [Date.t() | ICal.rfc5455_datetime | ICal.period()],
          rrule: ICal.Recurrence.t() | nil,
          class: String.t() | nil,
          description: String.t() | nil,
          duration: ICal.Duration.t() | nil,
          location: String.t() | nil,
          organizer: String.t() | nil,
          sequence: String.t() | nil,
          status: :tentative | :confirmed | :cancelled | nil,
          summary: String.t() | nil,
          url: String.t() | nil,
          geo: ICal.geo() | nil,
          priority: integer | nil,
          transparency: :opaque | :transparent | nil,
          alarms: [ICal.Alarm.t()],
          attachments: [ICal.Attachment.t()],
          attendees: [String.t()],
          categories: [String.t()],
          comments: [String.t()],
          contacts: [ICal.Contact.t()],
          related_to: [String.t()],
          request_status: [ICal.RequestStatus.t()],
          resources: [String.t()],
          custom_properties: ICal.custom_properties()
        }
end
